// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdfaaqzwzyhfcgjeeyvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZmFhcXp3enloZmNnamVleXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDgyMTQsImV4cCI6MjA3MTk4NDIxNH0.KogqwKmY6O-kKCe2Qjaa1KGfdX9zhZ3qFzuM2Tqh4S4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});